chat/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('get_chats_betweenUsers/', get_chats_betweenUsers, name='get_chats_betweenUsers'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('secret-admin/', admin.site.urls),

    # chat urls
    path('', include('mainApp.urls')),

    # auth urls
    path('auth/', include('users.urls')),

    # add friend urls
    path('add_friend/', include('add_friend_app.urls')),

    # chat urls
    path('chat/', include('chat.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import *
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from django.contrib.auth import views as auth_views

urlpatterns = [
    # views that handles registration and authorization
    path("signup/", SignUpView.as_view(), name="signup"),
    path("<str:email>/update_user/", VendorUpdateView.as_view(), name="update_users"),
    path("signin/", LoginView.as_view(), name="signin"),

    # just template views
    path('registration/', registration, name='registration'),
    path('login/', loginView, name='login'),
    path('logout/', logoutForm, name='logout'),

    # ეს არის ლინკი სადაც უნდა შევიყვანოთ ჩვენი იმეილი რათა მოხდეს იმეილის გაგზავნა
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="users/forget-password.html"), name='password_reset'),
    # აქ უკვე გამოჩნდება მესიჯი სადაც ეწერება რომ იმეილი გაიგზავნა
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/check-email.html"), name='password_reset_done'),
    # აქ ვაკეთებთ პაროლის შეცვლას
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/change-password.html"), name='password_reset_confirm'),
    # და ეს უკვე არის დასასრული და მერე გადავდივართ ლოგინ ფეიჯზე ისევ
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password-reset-done.html"), name='password_reset_complete'),

    # ამით ვქმნით ტოკენს
    path("jwt/create/", TokenObtainPairView.as_view(), name="jwt-create"),
    # ამით ვარეფრეშებთ ანუ ახალ ტოკენს ვიღებთ
    path("jwt/refresh/", TokenRefreshView.as_view(), name="jwt-refresh"),
    # ამით ვტესტავთ კარგია თუ არა ეს ახალი ტოკენი
    path("jwt/verify/", TokenVerifyView.as_view(), name="jwt-verify"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    email = models.EmailField(null=True, unique=True)
    friends = models.ManyToManyField('self', through='Friendship', symmetrical=False, related_name='friends_with', blank=True)

    friend_requests = models.ManyToManyField('self', through='FriendRequest', symmetrical=False, related_name='friends_requests', blank=True)
    
    full_name = models.CharField(max_length=255, default='None')

    bio = models.TextField(null=True, blank=True, default="No Bio For Now")
    avatar = models.ImageField(null=True, default='avatar.svg')

    # ანუ იუზერნეიმ ფიელდ იქნება ემაილი ეხლა
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()
    
    def save(self, *args, **kwargs):
        self.username = self.email  # Ensure username stays synced with email
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = _("Users")

    def __str__(self):
        return self.email
    
class Friendship(models.Model):
    # Intermediary table for the friendship relationship
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_friendships')
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend_friendships')
    # Add any additional fields for the friendship relationship here (e.g., date added)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.email} - {self.friend.email}'

class FriendRequest(models.Model):
    """A model to represent a sent or received friend request."""
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_friendrequest')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_friendreciever')

    rejected = models.BooleanField(default=False)
    accepted = models.BooleanField(default=False)

    #created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender.email} - {self.receiver.email}'

users/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm

class UsersForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'avatar', 'bio', 'full_name']

users/views.py
import bleach
from .forms import UsersForm

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .serializers import UserSerializer
from rest_framework import generics, status, mixins
from rest_framework.request import Request
from rest_framework.response import Response
from .models import User
from rest_framework.views import APIView
from .tokens import create_jwt_for_user


def sanitize_input(user_input):
    cleaned_input = bleach.clean(user_input, tags=['p', 'strong', 'em'], attributes={'*': ['class']})
    return cleaned_input

def registration(request):
    form = UsersForm()

    context = {"form": form}
    return render(request, 'users/registration.html', context)

def loginView(request):
    return render(request, 'users/login.html')

class SignUpView(generics.GenericAPIView):

    """
    View for user registration.
    """

    serializer_class = UserSerializer
    permission_classes = []

    def post(self, request: Request):
        data = request.data
        serializer = self.serializer_class(data=data)

        if serializer.is_valid():
            serializer.save()

            response = {"message": "User Created", "data": serializer.data}

            return Response(data=response, status=status.HTTP_201_CREATED)

        print(serializer)
        return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class LoginView(APIView):
    """
    View for user login and JWT token generation.
    """
    def post(self, request: Request):
        email = sanitize_input(request.data.get("email"))
        password = sanitize_input(request.data.get('password')) 

        user = authenticate(request, password=password, email=email)

        if user is not None:
            login(request, user)
            # When the user logs in, create tokens
            tokens = create_jwt_for_user(user)
            response = {
                "message": "User login successful",
                "user": email,
                "tokens": tokens,
            }

            return Response(data=response, status=status.HTTP_200_OK)
        else:
            return Response(
                data={"message": "Email or password is invalid"},
            )

def logoutForm(request):
    logout(request)
    return redirect('login')


from rest_framework import status
from .serializers import UserUpdateSerializer
from .permissions import VendorUpdatePermission
import os

class VendorUpdateView(APIView):
    permission_classes = [VendorUpdatePermission]

    def put(self, request, email):

        """
        mokled vaabdeitebt user profiles chveulebrivad magram tu poto araris mowodebuli mashin ubralod vigebt
        datadan da ase vanaxlet profiles
        """

        try:
            vendor = User.objects.get(email=email)
            
            # Create a copy of the request data
            data = request.data.copy()
            
            # Check if 'avatar' field exists in the data
            if 'avatar' in data:
                avatar_file = request.FILES.get('avatar')
                if avatar_file:
                    # Retrieve the path of the photo associated with the sub-product
                    photo_path = vendor.avatar.url

                    # Delete the photo file from the storage
                    if os.path.exists(f'static{photo_path}'):
                        os.remove(f'static{photo_path}')
                        
                    vendor.avatar = avatar_file
                # If the 'avatar' field is in data but has no file, remove it from data
                else:
                    data.pop('avatar')
            
            # Use the remaining data for the serializer
            serializer = UserUpdateSerializer(vendor, data=data, partial=True)
            
            if serializer.is_valid():
                serializer.save()
                response = {"message": "Vendor Updated", "data": serializer.data}
                return Response(data=response, status=status.HTTP_200_OK)
            
            # If serializer is not valid
            return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        
        except User.DoesNotExist:
            return Response(data={"error": "User not found"}, status=status.HTTP_404_NOT_FOUND)
        
        except Exception as e:
            print(f"Error updating user: {e}")
            return Response(data={"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

        
def update_user(request, email):
    user = User.objects.get(email=email)
    return render(request, 'users/update-user.html', {'vend': user})

users/templates/users/change-password.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <style>
      /* Add these styles to your CSS file or style block */
      .container {
        margin: 20px;
        padding: 20px;
        border: 1px solid #ccc;
        max-width: 400px;
      }

      .form-group {
        margin-bottom: 20px;
      }

      label {
        display: block;
        font-weight: bold;
      }

      input[type="password"] {
        width: 100%;
        padding: 8px;
        border-radius: 4px;
        border: 1px solid #ccc;
      }

      button {
        padding: 8px 16px;
        border-radius: 4px;
        background-color: #007bff;
        color: white;
        border: none;
        cursor: pointer;
      }

      .validation-messages {
        margin-top: 20px;
      }

      .error-message {
        color: red;
        margin-bottom: 5px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h4>Change Password</h4>
      <form method="post" class="form" id="form">
        {% csrf_token %}
        <div class="form-group">
          {{ form.new_password1.label_tag }} {{ form.new_password1 }}
        </div>
        <div class="form-group">
          {{ form.new_password2.label_tag }} {{ form.new_password2 }}
        </div>
        <button class="btn" type="submit">Submit</button>
      </form>
      <div class="validation-messages">
        {% for field in form %} {% for error in field.errors %}
        <p class="error-message">{{ error }}</p>
        {% endfor %} {% endfor %}
      </div>
    </div>
  </body>
</html>

users/templates/users/check-email.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    check your email
  </body>
</html>

users/templates/users/forget-password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
    />

    <link rel="stylesheet" href="{% static 'css/login3.css' %}" />

    <title>Forget Password</title>
  </head>
  <body>
    <div class="continer" style="margin: 100px auto; width: 70%">
      <form class="form" method="post" id="form">
        {% csrf_token %}
        <h4>Forget Password</h4>

        {% if messages %} {% for message in messages %}
        <div class="alert alert-info">{{ message }}</div>
        {% endfor %} {% endif %}

        <div class="form-group">
          <label for="password">Type Your Email</label>
          <input type="text" name="email" class="form-control" />
        </div>

        <button class="btn btn-info" type="submit">Submit</button>
      </form>
    </div>
  </body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Login Form</title>
    <link rel="stylesheet" href="{% static 'css/login3.css' %}" />
  </head>
  <body>
    <div class="container">
      <div class="login form">
        <header>Login</header>
        <form method="post">
          {% csrf_token %}
          <input
            type="text"
            id="email"
            name="email"
            placeholder="Enter your email"
          />
          <input
            type="password"
            id="password"
            name="password"
            placeholder="Enter your password"
          />
          <a href="{% url 'password_reset'%}">Forgot password?</a>
          <input type="button" class="button" value="Login" />
        </form>

        <p id="messages" style="color: red"></p>

        <div class="signup">
          <span class="signup"
            >Don't have an account?
            <a href="{% url 'registration' %}">Signup</a>
          </span>
        </div>
        <p id="error-message"></p>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      let email = document.querySelector("#email");
      let password1 = document.querySelector("#password");

      function sanitizeInput(userInput) {
        // Remove all HTML tags from user input
        let sanitizedInput = userInput.replace(/(<([^>]+)>)/gi, "");
        return sanitizedInput;
      }

      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          var cookies = document.cookie.split(";");
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Check if this cookie string begins with the name provided
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getCookie("csrftoken");

      // Clear any previous error messages
      document.getElementById("error-message").textContent = "";

      $(".button").on("click", function () {
        const emailVal = email.value;
        const pass1Val = password1.value;

        if (!emailVal || !pass1Val) {
          alert(
            "Please fill out all the fields!\n\n*Note: Passwords must be at least 8 characters long."
          );
          return false;
        } else if (pass1Val.length < 8) {
          alert(
            "Password is too short!\n\n*Note: Password should be at least 8 characters long."
          );
          return false;
        }

        $.ajax({
          url: `${location.protocol}//${location.host}/auth/signin/`,
          type: "POST",
          headers: { "X-CSRFToken": csrftoken },
          contentType: "application/json",
          data: JSON.stringify({
            email: sanitizeInput(emailVal),
            password: sanitizeInput(pass1Val),
          }),
          success: function (data) {
            console.log(data);

            if (data.message == "Email or password is invalid") {
              document.querySelector("#messages").textContent = data.message;
            } else {
              const token = data.tokens;
              localStorage.setItem("access_token", token.access); // Store securely
              localStorage.setItem("refresh_token", token.refresh); // Store securely
              window.location.href = "/"; // Redirect to secure area
            }
          },
          error: function (error) {
            console.error("Registration failed:", error);
            const message = error.response?.data?.message || "Login failed.";
            document.getElementById("error-message").textContent = message;
          },
        });
      });
    </script>
  </body>
</html>

users/templates/users/password-reset-done.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Password reset complete</h1>
    <p>
      Your password has been set. You may go ahead and log in now.
      <a href="{% url 'login' %}">Log in</a>
    </p>
  </body>
</html>

users/templates/users/registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Registration Form</title>
    <link rel="stylesheet" href="{% static 'css/login3.css' %}" />
  </head>
  <body>
    <div class="container cont_user">
      <div class="registration form">
        <header>Signup</header>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div>
            <label for="full_name">Full Name</label>
            {{form.full_name}} {{ form.full_name.errors }}
          </div>
          <div>
            <label for="avatar">Choose Your Avatar</label>
            {{form.avatar}} {{ form.avatar.errors }}
          </div>
          <div>{{form.email}} {{ form.email.errors }}</div>

          <div
            class="passwords"
            style="
              display: flex;
              gap: 1rem;
              align-items: center;
              justify-content: center;
            "
          >
            <div style="width: 100%">
              {{form.password1}} {{ form.password1.errors }}
            </div>
            <div style="width: 100%">
              {{form.password2}} {{ form.password2.errors }}
            </div>
          </div>

          <input type="button" class="button" value="Signup" />
        </form>
        <div class="signup">
          <span class="signup"
            >Already have an account?
            <a href="{% url 'login' %}">Login</a>
          </span>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      let email = document.querySelector("#id_email");
      let full_name = document.querySelector("#id_full_name");
      let avatar = document.querySelector("#id_avatar");
      let password1 = document.querySelector("#id_password1");
      let password2 = document.querySelector("#id_password2");
      email.placeholder = "Enter Your Email";
      password1.name = "password";
      password1.placeholder = "Enter your password";
      password2.placeholder = "Repeat your password";
      full_name.value = "";
      full_name.placeholder = "Your Full Name";

      function sanitizeInput(userInput) {
        // Remove all HTML tags from user input
        let sanitizedInput = userInput.replace(/(<([^>]+)>)/gi, "");
        return sanitizedInput;
      }

      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          var cookies = document.cookie.split(";");
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Check if this cookie string begins with the name provided
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getCookie("csrftoken");

      $(".button").on("click", function () {
        const emailVal = email.value;
        const pass1Val = password1.value;
        const pass2Val = password2.value;
        const full_nameVal = full_name.value;
        const avatarVal = avatar.value;

        if (!emailVal || !pass1Val || !pass2Val || !full_nameVal) {
          alert(
            "Please fill out all the fields!\n\n*Note: Passwords must be at least 8 characters long."
          );
          return false;
        } else if (pass1Val !== pass2Val) {
          alert("Passwords do not match!");
          return false;
        } else if (pass1Val.length < 8) {
          alert(
            "Password is too short!\n\n*Note: Password should be at least 8 characters long."
          );
          return false;
        }

        let formData = new FormData();
        if (avatar.files[0]) {
          formData.append("avatar", avatar.files[0]);
        }
        formData.append("email", sanitizeInput(emailVal));
        formData.append("password", sanitizeInput(pass1Val));
        formData.append("full_name", sanitizeInput(full_nameVal));

        $.ajax({
          url: `${location.protocol}//${location.host}/auth/signup/`,
          type: "POST",
          headers: { "X-CSRFToken": csrftoken },
          contentType: false,
          processData: false,
          data: formData,
          success: function (data) {
            window.location.href = `${location.protocol}//${location.host}/auth/login/`;
          },
          error: function (error) {
            console.error("Registration failed:", error);
          },
        });
      });
    </script>
  </body>
</html>

users/templates/users/update-user.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Update Form</title>
    <link rel="stylesheet" href="{% static 'css/login3.css' %}" />
  </head>
  <body>
    <div class="container">
      <div class="registration form">
        <header
          style="
            display: flex;
            align-items: center;
            justify-content: space-between;
          "
        >
          <a href="{% url 'home' %}">Go Home</a>
          <span> Update </span>
        </header>
        <form method="post">
          {% csrf_token %}

          <input
            type="hidden"
            name="email"
            id="vend_email"
            value="{{vend.email}}"
          />

          <input
            type="text"
            id="full_name"
            placeholder="Full Name"
            style="margin-bottom: 0.7rem"
            value="{{vend.full_name}}"
          /><br />
          <textarea
            id="description"
            placeholder="Bio"
            style="
              width: 100%;
              padding: 15px 15px 0 15px;
              font-size: 15px;
              margin-bottom: 0.3rem;
              border: 1px solid #ddd;
              border-radius: 6px;
              outline: none;
            "
          >
{{vend.bio}}</textarea
          ><br />
          <input
            type="text"
            id="avatar"
            placeholder="avatar"
            value="{{vend.avatar}}"
          /><br />
          <input type="button" class="button" value="Update" />
        </form>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      let full_name = document.querySelector("#full_name");
      let description = document.querySelector("#description");
      let avatar = document.querySelector("#avatar");

      function sanitizeInput(userInput) {
        // Remove all HTML tags from user input
        let sanitizedInput = userInput.replace(/(<([^>]+)>)/gi, "");
        return sanitizedInput;
      }

      let jwtToken = localStorage.getItem("access_token");

      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          var cookies = document.cookie.split(";");
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Check if this cookie string begins with the name provided
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getCookie("csrftoken");

      $(".button").on("click", function () {
        const descriptionVal = description.value;
        const full_nameVal = full_name.value;
        const avatarVal = avatar.value;
        const vend_email = document.querySelector("#vend_email").value;

        if (!full_nameVal) {
          alert(
            "Please fill shop name field!\n\n*Note: Shop Name Should Not Have Special Characters."
          );
          return false;
        }

        //var formData = new FormData();
        //formData.append("image", product_image.files[0]);
        //formData.append("product_obj", JSON.stringify(product_obj));

        var formData = {
          "full_name": sanitizeInput(full_nameVal).replace(/['"]/g, ""),
          "description": sanitizeInput(descriptionVal),
          "avatar": sanitizeInput(avatarVal),
        };

        $.ajax({
          url: `${location.protocol}//${location.host}/auth/${sanitizeInput(
            vend_email
          )}/update_vendor/`,
          type: "PUT",
          headers: {
            "X-CSRFToken": csrftoken,
            "Authorization": `Bearer ${jwtToken}`,
          },
          contentType: "application/json",
          data: JSON.stringify(formData),
          success: function (data) {
            window.location.href = `/`;
          },
          error: function (xhr, status, error) {
            // Given token not valid for any token type

            try {
              if (
                xhr.responseJSON.detail ==
                "Given token not valid for any token type"
              ) {
                window.location.href = `${location.protocol}//${location.host}/auth/logout/`;
              }
            } catch (error) {
              console.log(error);
            }

            // Handle error response from the backend
            // console.error("Error sending data:", error.erro12r);
            // // Optionally, you can display an error message to the user

            if (xhr.responseJSON.non_field_errors[0]) {
              alert(`Error: ${xhr.responseJSON.non_field_errors[0]}`);
            }
          },
        });
      });
    </script>
  </body>
</html>